language: python
python:
- '3.6'
before_install:
- cd tests/
- openssl aes-256-cbc -K $encrypted_d2ff316999ca_key -iv $encrypted_d2ff316999ca_iv -in secrets.tar.gz.enc -out secrets.tar.gz -d
- tar xvf secrets.tar.gz
- cd ../
install:
- pip install -r requirements.txt
- python setup.py build install
script:
- cd tests/
- pytest
